global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#vladimir_denisov'
