global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'
  routes:
    - match:
      continue: true
      receiver: 'slack-notifications'
    - match:
      receiver: 'email'


receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#vladimir_denisov'

  - name: 'email'
    email_configs:
      - to: $GMAIL_ACCOUNT
        from: $GMAIL_ACCOUNT
        smarthost: smtp.gmail.com:587
        auth_username: "$GMAIL_ACCOUNT"
        auth_identity: "$GMAIL_ACCOUNT"
        auth_password: "$GMAIL_AUTH_TOKEN"
