version: '3.3'
services:

  post_db:
    image: "mongo:${mongodb_version:-latest}"
    volumes:
      - post_db:/data/db
    networks:
      back_net:
          aliases:
            - comment_db

  ui:
    image: "${USER_NAME}/ui:${ui_version:-2.2}"
    ports:
      - "${ui_port:-9292}:9292/tcp"
    networks:
      - front_net

  post:
    image: "${USER_NAME}/post:${post_version:-2.2}"
    networks:
      - back_net
      - front_net

  comment:
    image: "${USER_NAME}/comment:${comment_version:-2.2}"
    networks:
      - front_net
      - back_net

volumes:
  post_db:

networks:
  front_net:
    external:
      name: frontend
  back_net:
    external:
      name: backend
